# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lyapunov_cpp <- function(A, Q, P, lambda_r, lambda_i, stop_if_non_stable) {
    .Call(`_rationalmatrices_lyapunov_cpp`, A, Q, P, lambda_r, lambda_i, stop_if_non_stable)
}

lyapunov_Jacobian_cpp <- function(A, Q, P, dA, dQ, J, lambda_r, lambda_i, stop_if_non_stable) {
    .Call(`_rationalmatrices_lyapunov_Jacobian_cpp`, A, Q, P, dA, dQ, J, lambda_r, lambda_i, stop_if_non_stable)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_rationalmatrices_RcppExport_registerCCallable`)
})
